-- 爬虫批量作业的执行留痕（每次 crawl:all / crawl:prices / import 各记一条汇总）。
-- 与 crawl_job_run 不同：本表【不会】被 import-data-pg 的 TRUNCATE 清空，
-- 因此可用来回答"最近一次什么时候跑的、有没有失败"。

CREATE TABLE IF NOT EXISTS crawl.crawl_run_log (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind          VARCHAR(32)  NOT NULL,           -- crawl_all / crawl_prices / import
  scope         VARCHAR(255),                    -- 品牌/范围，如 all / tjoy / aeon,c109
  tasks         VARCHAR(255),                    -- 本次涉及的任务类型，如 cinemas,info,schedule,movies,prices
  status        SMALLINT     NOT NULL DEFAULT 1, -- 1 运行中 / 2 成功 / 3 失败 / 4 部分成功
  started_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at   TIMESTAMP,
  duration_ms   BIGINT,
  ok_count      INTEGER      NOT NULL DEFAULT 0,
  fail_count    INTEGER      NOT NULL DEFAULT 0,
  skipped_count INTEGER      NOT NULL DEFAULT 0,
  total_count   INTEGER      NOT NULL DEFAULT 0,
  summary_json  JSONB,                           -- 按品牌聚合等概览
  failures_json JSONB,                           -- 失败明细 [{brand,task,cinema,error}]
  error_msg     VARCHAR(2048),                   -- 整体 fatal（非单任务失败）
  host_name     VARCHAR(128),                    -- 执行机器名，便于多机区分
  create_time   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crawl_run_log_kind_started
  ON crawl.crawl_run_log (kind, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_crawl_run_log_started
  ON crawl.crawl_run_log (started_at DESC);

COMMENT ON TABLE crawl.crawl_run_log IS
  '爬虫批量作业执行留痕；不被 import TRUNCATE，用于判断最近执行时间与成败';
COMMENT ON COLUMN crawl.crawl_run_log.status IS
  '1 运行中 / 2 成功 / 3 失败 / 4 部分成功';
