-- C 端「收藏影院」。绑定 cinema_id（importer 按 cinema_key upsert，全量导入不再 TRUNCATE cinema，id 保持稳定）。
-- 与 user_cinema（admin 运营账号数据权限）语义不同。

CREATE TABLE IF NOT EXISTS public.user_favorite_cinema (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER      NOT NULL,
  cinema_id   INTEGER      NOT NULL,
  create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  deleted     INTEGER      DEFAULT 0,
  CONSTRAINT user_favorite_cinema_cinema_id_fkey
    FOREIGN KEY (cinema_id) REFERENCES public.cinema(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_favorite_cinema_user_cinema
  ON public.user_favorite_cinema (user_id, cinema_id) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_user_favorite_cinema_user
  ON public.user_favorite_cinema (user_id) WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS crawl.user_favorite_cinema (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER      NOT NULL,
  cinema_id   INTEGER      NOT NULL,
  create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  deleted     INTEGER      DEFAULT 0,
  CONSTRAINT crawl_user_favorite_cinema_cinema_id_fkey
    FOREIGN KEY (cinema_id) REFERENCES crawl.cinema(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_crawl_user_favorite_cinema_user_cinema
  ON crawl.user_favorite_cinema (user_id, cinema_id) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_crawl_user_favorite_cinema_user
  ON crawl.user_favorite_cinema (user_id) WHERE deleted = 0;

COMMENT ON TABLE crawl.user_favorite_cinema IS 'C 端用户收藏影院（绑定 cinema_id）';
COMMENT ON TABLE public.user_favorite_cinema IS 'C 端用户收藏影院（绑定 cinema_id）';
