-- 2026-05-28: 订单主键从 order_number 切换到 BIGINT id。
-- 历史本地/测试库的 movie_order 主键建在 order_number 上，id 仅为普通 BIGINT 列且无 IDENTITY。
-- 本迁移做以下事情，幂等且兼容已经按 V1 baseline 建好的新库：
--   1) 临时去掉指向 movie_order 的外键，避免修改约束时被阻塞
--   2) 把 id 调整为 BIGINT NOT NULL，并附加 IDENTITY（若缺失），让 MyBatis-Plus IdType.AUTO 可用
--   3) 删除旧的 order_number 主键，改建在 id 上
--   4) 保证 order_number 仍然唯一
--   5) 重新建立 select_seat / refund 对 movie_order 的外键

ALTER TABLE IF EXISTS select_seat
  DROP CONSTRAINT IF EXISTS select_seat_movie_order_id_fkey;

ALTER TABLE IF EXISTS refund
  DROP CONSTRAINT IF EXISTS refund_order_number_fkey;

-- 1) 确保 movie_order.id 存在且为 BIGINT
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'movie_order'
  ) THEN
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'movie_order'
      AND column_name = 'id'
  ) THEN
    ALTER TABLE movie_order ADD COLUMN id BIGINT;
  ELSE
    ALTER TABLE movie_order ALTER COLUMN id TYPE BIGINT;
  END IF;
END $$;

-- 2) 回填 id（若有 NULL 行），然后 NOT NULL，再附加 IDENTITY
DO $$
DECLARE
  v_max_id      bigint;
  v_is_identity text;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'movie_order'
      AND column_name = 'id'
  ) THEN
    RETURN;
  END IF;

  SELECT COALESCE(MAX(id), 0) INTO v_max_id FROM movie_order;

  UPDATE movie_order mo
     SET id = v_max_id + sub.rn
    FROM (
      SELECT ctid, ROW_NUMBER() OVER (ORDER BY ctid) AS rn
      FROM movie_order
      WHERE id IS NULL
    ) sub
   WHERE mo.ctid = sub.ctid;

  ALTER TABLE movie_order ALTER COLUMN id SET NOT NULL;

  SELECT is_identity INTO v_is_identity
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'movie_order'
    AND column_name = 'id';

  IF v_is_identity IS DISTINCT FROM 'YES' THEN
    -- 旧库里 id 可能已经挂了 nextval('xxx_seq') 这类默认值，
    -- 而 PostgreSQL 不允许同一列既有 DEFAULT 又转 IDENTITY，所以先清掉默认值。
    ALTER TABLE movie_order ALTER COLUMN id DROP DEFAULT;

    EXECUTE format(
      'ALTER TABLE movie_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      (SELECT COALESCE(MAX(id), 0) + 1 FROM movie_order)
    );
  END IF;
END $$;

-- 3) 把主键从 order_number 切换到 id
DO $$
DECLARE
  v_pk_name text;
  v_pk_cols text;
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'movie_order'
  ) THEN
    RETURN;
  END IF;

  SELECT c.conname,
         (SELECT string_agg(a.attname, ',' ORDER BY array_position(c.conkey, a.attnum))
            FROM pg_attribute a
           WHERE a.attrelid = c.conrelid
             AND a.attnum = ANY (c.conkey))
    INTO v_pk_name, v_pk_cols
    FROM pg_constraint c
   WHERE c.conrelid = 'public.movie_order'::regclass
     AND c.contype = 'p';

  IF v_pk_name IS NOT NULL AND v_pk_cols IS DISTINCT FROM 'id' THEN
    EXECUTE format('ALTER TABLE movie_order DROP CONSTRAINT %I', v_pk_name);
    v_pk_name := NULL;
  END IF;

  IF v_pk_name IS NULL THEN
    ALTER TABLE movie_order
      ADD CONSTRAINT movie_order_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- 4) order_number 保持唯一（原 PK 被丢弃后需补 UNIQUE）
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'movie_order'
  ) THEN
    RETURN;
  END IF;

  IF NOT EXISTS (
    SELECT 1
      FROM pg_constraint c
      JOIN pg_attribute a
        ON a.attrelid = c.conrelid
       AND a.attnum   = ANY (c.conkey)
     WHERE c.conrelid = 'public.movie_order'::regclass
       AND c.contype IN ('p', 'u')
       AND array_length(c.conkey, 1) = 1
       AND a.attname = 'order_number'
  ) THEN
    ALTER TABLE movie_order
      ADD CONSTRAINT movie_order_order_number_key UNIQUE (order_number);
  END IF;
END $$;

-- 5) 同步 select_seat.movie_order_id 为 BIGINT，并重建外键
ALTER TABLE IF EXISTS select_seat
  ALTER COLUMN movie_order_id TYPE BIGINT;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'select_seat'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'select_seat_movie_order_id_fkey'
  ) THEN
    ALTER TABLE select_seat
      ADD CONSTRAINT select_seat_movie_order_id_fkey
      FOREIGN KEY (movie_order_id) REFERENCES movie_order(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 6) 重建 refund -> movie_order(order_number) 外键
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'refund'
  ) AND NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'refund_order_number_fkey'
  ) THEN
    ALTER TABLE refund
      ADD CONSTRAINT refund_order_number_fkey
      FOREIGN KEY (order_number) REFERENCES movie_order(order_number) ON DELETE CASCADE;
  END IF;
END $$;
