-- ============================================================
-- V4: 预售券表
--
-- 当前 dev 连接串使用 currentSchema=crawl，MovieMapper.xml 中的
-- `LEFT JOIN presale` 会解析到 crawl.presale。此前 crawl schema
-- 没有创建预售表，导致 App 首页查询时报：
--   ERROR: relation "presale" does not exist
-- ============================================================

SET timezone = 'Asia/Tokyo';

CREATE SCHEMA IF NOT EXISTS crawl;

CREATE TABLE IF NOT EXISTS crawl.presale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    delivery_type INTEGER NOT NULL DEFAULT 1,
    discount_mode INTEGER DEFAULT 1,
    mubitike_type INTEGER DEFAULT 1,
    price DECIMAL(10,2) NOT NULL DEFAULT 0,
    amount DECIMAL(10,2),
    total_quantity INTEGER NOT NULL DEFAULT 0,
    launch_time TIMESTAMP,
    end_time TIMESTAMP,
    usage_start TIMESTAMP,
    usage_end TIMESTAMP,
    per_user_limit INTEGER NOT NULL DEFAULT 1,
    movie_id INTEGER,
    pickup_notes TEXT,
    cover VARCHAR(500),
    gallery TEXT[],
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0,
    CONSTRAINT fk_crawl_presale_movie
        FOREIGN KEY (movie_id) REFERENCES crawl.movie(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS crawl.presale_specification (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presale_id INTEGER NOT NULL,
    name VARCHAR(255),
    sku_code VARCHAR(64),
    ticket_type INTEGER,
    delivery_type INTEGER NOT NULL DEFAULT 1,
    stock INTEGER,
    points INTEGER,
    ship_days INTEGER,
    images TEXT[],
    bonus_title VARCHAR(255),
    bonus_images TEXT[],
    bonus_description TEXT,
    bonus_quantity INTEGER,
    price_items JSONB,
    bonus_included BOOLEAN DEFAULT TRUE,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted INTEGER DEFAULT 0,
    CONSTRAINT fk_crawl_presale_specification_presale
        FOREIGN KEY (presale_id) REFERENCES crawl.presale(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_crawl_presale_movie
    ON crawl.presale (movie_id)
    WHERE movie_id IS NOT NULL AND deleted = 0;

CREATE INDEX IF NOT EXISTS idx_crawl_presale_deleted
    ON crawl.presale (deleted);

CREATE INDEX IF NOT EXISTS idx_crawl_presale_specification_presale
    ON crawl.presale_specification (presale_id)
    WHERE deleted = 0;

COMMENT ON TABLE crawl.presale IS '预售券主表';
COMMENT ON COLUMN crawl.presale.delivery_type IS 'dict_item.code，presaleDeliveryType：1=虚拟 2=实体';
COMMENT ON COLUMN crawl.presale.discount_mode IS 'dict_item.code，presaleDiscountMode：1=固定 2=比例';
COMMENT ON COLUMN crawl.presale.mubitike_type IS 'dict_item.code，presaleMubitikeType';
COMMENT ON COLUMN crawl.presale.movie_id IS '适用电影ID（仅一个）';

COMMENT ON TABLE crawl.presale_specification IS '预售券规格/SKU';
COMMENT ON COLUMN crawl.presale_specification.ticket_type IS 'dict_item.code，presaleMubitikeType';
COMMENT ON COLUMN crawl.presale_specification.delivery_type IS 'dict_item.code，presaleDeliveryType：1=虚拟 2=实体';
COMMENT ON COLUMN crawl.presale_specification.price_items IS '多档价格 JSONB，例如 [{label,price}]';
