-- ============================================================
-- V5: 把历史上绕过 Flyway、直接加到 public 的 11 张业务表纳入版本控制
--
-- 背景：
--   排查 crawl schema 镜像缺口时发现，public 里这 11 张表既不在 V1
--   baseline，也没有任何 Vx 迁移创建它们，应该是早期通过 JPA 自动 DDL
--   或手工执行落地的。导致：
--     1) 全新数据库走 Flyway 不会创建这些表；
--     2) V3 的 crawl 镜像没法覆盖到这些表（见 V6）。
--
--   本迁移把这 11 张表"反查"出真实结构，作为 V1 的补丁登记进 Flyway。
--   全部使用 IF NOT EXISTS，已经包含这些表的老数据库为 no-op；新数据库
--   会按本脚本创建出与 V1 baseline 风格一致的 IDENTITY 主键结构。
--
-- 表清单：
--   auth_provider_config          App 登录方式显示配置
--   benefit                       入场者特典阶段
--   benefit_theater_stock         特典影院库存
--   benefit_user_feedback         用户特典纠错反馈
--   cinema_price_rules_config     影院价格规则配置
--   movie_comment_like            评论点赞（旧表，无主键，保留原状）
--   movie_show_time_ticket_type   场次限定票种规则
--   payment_methods               支付方式（与 V1 的 payment_method 是两张表）
--   pricing_rule                  定价规则
--   rls_audit_log                 RLS 权限审计日志
--   rule_conflict_log             规则冲突日志
-- ============================================================

SET timezone = 'Asia/Tokyo';

-- ----------------------------------------------------------------
-- App 登录方式显示配置
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auth_provider_config (
    id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(32)   NOT NULL,
    name            VARCHAR(64)   NOT NULL,
    enabled         BOOLEAN       NOT NULL DEFAULT TRUE,
    platform        VARCHAR(20)   NOT NULL DEFAULT 'ALL',
    sort            INTEGER       NOT NULL DEFAULT 0,
    min_app_version VARCHAR(32),
    remark          VARCHAR(255),
    create_time     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    deleted         INTEGER       DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_auth_provider_config_code
    ON auth_provider_config (code) WHERE deleted = 0;

COMMENT ON TABLE auth_provider_config IS 'App 登录方式显示配置';

-- ----------------------------------------------------------------
-- 入场者特典阶段（第几弹）
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS benefit (
    id                INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id          INTEGER     NOT NULL,
    name              VARCHAR(128) NOT NULL,
    start_date        VARCHAR(32) NOT NULL,
    end_date          VARCHAR(32),
    order_num         INTEGER     DEFAULT 0,
    create_time       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    update_time       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    deleted           INTEGER     NOT NULL DEFAULT 0,
    quantity          INTEGER,
    description       TEXT,
    image_urls        JSONB,
    dimension_type    INTEGER,
    spec_ids          JSONB,
    cinema_limit_type SMALLINT    DEFAULT 0,
    cinema_ids        JSONB,
    remaining         INTEGER,
    phase_status      INTEGER,
    re_release_id     INTEGER,
    CONSTRAINT benefit_movie_id_fkey
        FOREIGN KEY (movie_id) REFERENCES movie(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_benefit_movie_dates
    ON benefit (movie_id, start_date, end_date) WHERE deleted = 0;
CREATE INDEX IF NOT EXISTS idx_benefit_movie_rerelease
    ON benefit (movie_id, re_release_id) WHERE deleted = 0;

COMMENT ON TABLE benefit IS '入场者特典阶段（第几弹）';

-- ----------------------------------------------------------------
-- 特典影院库存（按影院+物料）
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS benefit_theater_stock (
    id              INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id       INTEGER     NOT NULL,
    quota           INTEGER     DEFAULT 0,
    remaining       INTEGER     DEFAULT 0,
    create_time     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    deleted         INTEGER     NOT NULL DEFAULT 0,
    benefit_id      INTEGER     NOT NULL,
    manual_sold_out SMALLINT    NOT NULL DEFAULT 0,
    CONSTRAINT benefit_theater_stock_cinema_id_fkey
        FOREIGN KEY (cinema_id) REFERENCES cinema(id) ON DELETE CASCADE,
    CONSTRAINT fk_benefit_theater_stock_benefit
        FOREIGN KEY (benefit_id) REFERENCES benefit(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_benefit_stock_cinema
    ON benefit_theater_stock (cinema_id) WHERE deleted = 0;
CREATE UNIQUE INDEX IF NOT EXISTS uq_benefit_theater_stock_cinema_benefit
    ON benefit_theater_stock (cinema_id, benefit_id) WHERE deleted = 0;

COMMENT ON TABLE benefit_theater_stock IS '特典影院库存（按影院+物料）';

-- ----------------------------------------------------------------
-- 用户特典纠错反馈
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS benefit_user_feedback (
    id            INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER     NOT NULL,
    cinema_id     INTEGER     NOT NULL,
    feedback_type INTEGER     NOT NULL DEFAULT 1,
    create_time   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    deleted       INTEGER     NOT NULL DEFAULT 0,
    benefit_id    INTEGER     NOT NULL,
    CONSTRAINT benefit_user_feedback_cinema_id_fkey
        FOREIGN KEY (cinema_id) REFERENCES cinema(id) ON DELETE CASCADE,
    CONSTRAINT fk_benefit_user_feedback_benefit
        FOREIGN KEY (benefit_id) REFERENCES benefit(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_benefit_feedback_cinema_benefit
    ON benefit_user_feedback (cinema_id, benefit_id) WHERE deleted = 0;
CREATE UNIQUE INDEX IF NOT EXISTS uk_benefit_user_feedback_user_cinema_benefit_type
    ON benefit_user_feedback (user_id, cinema_id, benefit_id, feedback_type) WHERE deleted = 0;

COMMENT ON TABLE benefit_user_feedback IS '用户特典纠错反馈';

-- ----------------------------------------------------------------
-- 影院价格规则配置（一影院一行）
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cinema_price_rules_config (
    id                       INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id                INTEGER     NOT NULL,
    remark                   VARCHAR(500),
    allow_muviticket         BOOLEAN     DEFAULT FALSE,
    monthly_priority         INTEGER     DEFAULT 0,
    weekly_priority          INTEGER     DEFAULT 0,
    specific_date_priority   INTEGER     DEFAULT 0,
    time_range_priority      INTEGER     DEFAULT 0,
    fixed_price_priority     INTEGER     DEFAULT 0,
    ticket_type_priority     INTEGER     DEFAULT 0,
    create_time              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    update_time              TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    deleted                  INTEGER     DEFAULT 0,
    CONSTRAINT cinema_price_rules_config_cinema_id_key UNIQUE (cinema_id),
    CONSTRAINT cinema_price_rules_config_cinema_id_fkey
        FOREIGN KEY (cinema_id) REFERENCES cinema(id) ON DELETE CASCADE
);

COMMENT ON TABLE cinema_price_rules_config IS '影院价格规则配置：一影院一行，规则类型优先级、是否前售券等';

-- ----------------------------------------------------------------
-- 评论点赞（旧表，原本没有主键，保留原状以兼容现有数据）
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS movie_comment_like (
    type             VARCHAR(255)                NOT NULL,
    "like"           BOOLEAN                     NOT NULL DEFAULT FALSE,
    unlike           BOOLEAN                     NOT NULL DEFAULT FALSE,
    movie_comment_id INTEGER,
    movie_reply_id   INTEGER,
    user_id          INTEGER                     NOT NULL,
    create_time      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    update_time      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "actionType"     VARCHAR                     NOT NULL
);

-- ----------------------------------------------------------------
-- 场次限定票种规则：覆盖价与本场次启用开关
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS movie_show_time_ticket_type (
    id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_time_id    INTEGER       NOT NULL,
    ticket_type_id  INTEGER       NOT NULL,
    override_price  NUMERIC(10,2),
    enabled         BOOLEAN       NOT NULL DEFAULT TRUE,
    create_time     TIMESTAMP,
    update_time     TIMESTAMP,
    deleted         INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT movie_show_time_ticket_type_show_time_id_fkey
        FOREIGN KEY (show_time_id) REFERENCES movie_show_time(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_show_time_ticket_type
    ON movie_show_time_ticket_type (show_time_id, ticket_type_id) WHERE deleted = 0;

COMMENT ON TABLE movie_show_time_ticket_type IS '场次限定票种规则：覆盖价与本场次启用开关';

-- ----------------------------------------------------------------
-- 支付方式（独立于 V1 的 payment_method；两张表不同）
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_methods (
    id          INTEGER                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    create_time TIMESTAMP(6) WITH TIME ZONE DEFAULT now(),
    update_time TIMESTAMP(6) WITH TIME ZONE DEFAULT now(),
    deleted     SMALLINT                    DEFAULT 0,
    icon        VARCHAR(255),
    disabled    BOOLEAN                     DEFAULT FALSE
);

-- ----------------------------------------------------------------
-- 定价规则：适用人群、票价、匹配优先级
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pricing_rule (
    id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audience_type INTEGER       NOT NULL,
    value         NUMERIC(10,2) NOT NULL,
    priority      INTEGER       NOT NULL DEFAULT 0,
    create_time   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    deleted       INTEGER       DEFAULT 0,
    cinema_id     INTEGER       NOT NULL,
    CONSTRAINT pricing_rule_cinema_id_fkey
        FOREIGN KEY (cinema_id) REFERENCES cinema(id) ON DELETE CASCADE
);

COMMENT ON TABLE pricing_rule IS '定价规则：适用人群、票价、匹配优先级(越小越优先)';

-- ----------------------------------------------------------------
-- RLS 权限审计日志（来自 ROW_LEVEL_PERMISSION_DESIGN）
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rls_audit_log (
    id                  INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             INTEGER     NOT NULL,
    original_level      VARCHAR(20) NOT NULL,
    impersonated_level  VARCHAR(20),
    impersonated_org_id INTEGER,
    action              VARCHAR(50) NOT NULL,
    table_name          VARCHAR(100),
    record_id           INTEGER,
    created_at          TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- ----------------------------------------------------------------
-- 规则冲突日志（连锁规则 vs 影院规则的解决记录）
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rule_conflict_log (
    id              INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cinema_id       INTEGER     NOT NULL,
    chain_rule_id   INTEGER,
    cinema_rule_id  INTEGER,
    conflict_type   VARCHAR(50),
    resolution      VARCHAR(20) DEFAULT 'cinema_wins',
    resolved_at     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

DO $$
BEGIN
  RAISE NOTICE 'V5: public extra tables registered';
END $$;
