-- 电影去重合并二期：
-- 1) movie_merge_log：记录每一次后台人工合并，方便审计和排错。
-- 2) movie_merge_alias：把人工合并过的脏名/别名固化成导入规则；crawler 读取后，
--    同一个脏标题下次会直接落到 survivor 的 movie_key / tmdb_id。
-- 3) pending_movie_match：crawler 对 85%~95% 相似但不敢自动合并的标题写入这里，
--    后台「待确认」Tab 决定合并或忽略。
--
-- 全部建在 crawl schema；IF NOT EXISTS / partial unique index 保证幂等。

CREATE TABLE IF NOT EXISTS crawl.movie_merge_log (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  survivor_movie_id   INTEGER NOT NULL,
  loser_movie_id      INTEGER NOT NULL,
  survivor_movie_key  VARCHAR(160),
  loser_movie_key     VARCHAR(160),
  survivor_tmdb_id    INTEGER,
  loser_tmdb_id       INTEGER,
  survivor_name       VARCHAR(255),
  loser_name          VARCHAR(255),
  operator_user_id    INTEGER,
  note                VARCHAR(255),
  create_time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_movie_merge_log_survivor
  ON crawl.movie_merge_log (survivor_movie_id);
CREATE INDEX IF NOT EXISTS idx_movie_merge_log_loser
  ON crawl.movie_merge_log (loser_movie_id);

CREATE TABLE IF NOT EXISTS crawl.movie_merge_alias (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alias_title         VARCHAR(255) NOT NULL,
  survivor_movie_id   INTEGER,
  survivor_movie_key  VARCHAR(160),
  survivor_tmdb_id    INTEGER,
  source              VARCHAR(32) NOT NULL DEFAULT 'admin_merge',
  deleted             INTEGER NOT NULL DEFAULT 0,
  create_time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_movie_merge_alias_title_active
  ON crawl.movie_merge_alias (lower(btrim(alias_title)))
  WHERE deleted = 0;

CREATE INDEX IF NOT EXISTS idx_movie_merge_alias_movie_key
  ON crawl.movie_merge_alias (survivor_movie_key)
  WHERE deleted = 0 AND survivor_movie_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS crawl.pending_movie_match (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_movie_id  INTEGER NOT NULL,
  matched_movie_id    INTEGER NOT NULL,
  candidate_movie_key VARCHAR(160),
  matched_movie_key   VARCHAR(160),
  candidate_title     VARCHAR(255) NOT NULL,
  matched_title       VARCHAR(255) NOT NULL,
  confidence          NUMERIC(4,3) NOT NULL,
  match_reason        VARCHAR(32) NOT NULL,
  status              VARCHAR(16) NOT NULL DEFAULT 'PENDING',
  decided_by          INTEGER,
  decided_at          TIMESTAMP,
  create_time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_pending_movie_match_status
    CHECK (status IN ('PENDING', 'MERGED', 'IGNORED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_pending_movie_match_pair_pending
  ON crawl.pending_movie_match (
    LEAST(candidate_movie_id, matched_movie_id),
    GREATEST(candidate_movie_id, matched_movie_id),
    match_reason
  )
  WHERE status = 'PENDING';

CREATE INDEX IF NOT EXISTS idx_pending_movie_match_status
  ON crawl.pending_movie_match (status, update_time DESC);
